# Generated by Django 2.0.6 on 2019-02-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=45)),
                ('realName', models.CharField(max_length=100)),
                ('accountNumber', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
